spring:
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    data: classpath*:db/local/employee.sql
    